version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=parking
      - MYSQL_DATABASE=parking
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
